[package]
name = "aoc21_4"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aoc21_41"
path = "src/41.rs"

[[bin]]
name = "aoc21_42"
path = "src/42.rs"

[dependencies]