[package]
name = "aoc21_3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aoc21_31"
path = "src/31.rs"

[[bin]]
name = "aoc21_32"
path = "src/32.rs"

[dependencies]