[package]
name = "aoc21_6"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aoc21_61"
path = "src/61.rs"

[[bin]]
name = "aoc21_62"
path = "src/62.rs"

[dependencies]