[package]
name = "aoc21_1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aoc21_11"
path = "src/11.rs"

[[bin]]
name = "aoc21_12"
path = "src/12.rs"

[dependencies]