[package]
name = "aoc21_2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aoc21_21"
path = "src/21.rs"

[[bin]]
name = "aoc21_22"
path = "src/22.rs"

[dependencies]